apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-plex
  labels:
    app: kube-plex
roleRef:
  name: kube-plex
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: kube-plex
    namespace: "plex"
    kind: ServiceAccount
