apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-plex
  labels:
    app: kube-plex
rules:
  - resources:
      - pods
      - pods/attach
      - pods/exec
      - pods/portforward
      - pods/proxy
    apiGroups:
      - ""
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - resources:
      - jobs
    apiGroups:
      - batch
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
